language: node_js
node_js: 
  - "stable"

script: echo "Running tests against $(node -v)..."

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
      
cache:
  directories:
    - "node_modules"